services:
  redis:
    container_name: redis
    image: redis:8.2.1
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:17.6
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-gwando}
    restart: unless-stopped
  gwando:
    container_name: gwando
    build: .
    ports:
      - 8000:8000
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_NAME: ${DATABASE_NAME:-gwando}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_CHANNEL_NAME: ${REDIS_CHANNEL_NAME:-gwando}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/healthy"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
volumes:
  redis_data:
    name: redis_data
  postgres_data:
    name: postgres_data
